### PR TITLE
review

### PR DESCRIPTION
**Pull request by boledovicpantheon**

### CODE REVIEW

**Review by pmikus — CHANGES_REQUESTED** [review]
Why there is vagrantfile and .vagrant?

**Comment by boledovicpantheon** [comment]
Look into branch named "review"

**Comment by boledovicpantheon** [comment]
> Why there is vagrantfile and .vagrant?

I found in docs that you should have Vagrantfile in same directory as ansible playbooks. That's why I copied it here.

**Comment by pmikus** [comment]
> > Why there is vagrantfile and .vagrant?
> 
> I found in docs that you should have Vagrantfile in same directory as ansible playbooks. That's why I copied it here.

Yes but you have Vagrantfile in different repo. We do not want the copy of it. So please figure out how to do it properly (hint: there is one solution).
Also remove .vagrant/ which you do not need at all

**Comment by boledovicpantheon** [comment]
@pmikus You can review it now, everything should be fixed.

**Review by pmikus — APPROVED** [review]

**Comment by pmikus** [comment]
ok to merge

**Pull request merged**
